### ISSUE TITLE
Issue with deploying war

### ISSUE THREAD

**Issue by yangufsu** [bgawel/yeoman-frontend#7]
We have problem with deployed war file. It shows "An error has occurred" on the landing home page. When running in the dev mode using grails run-app, there is no issue at all. However, after grails war to package war file and deployed to glass fish server, the frontend is not working. Here is the stack trace:
[2017-08-25T10:54:49.923-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=26 _ThreadName=http-listener-1(1)] [timeMillis: 1503672889923] [levelValue: 900] [[
  StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
org.codehaus.groovy.grails.web.mapping.exceptions.UrlMappingException: Error mapping onto view [/index]: Error processing GroovyPageView: Error executing tag <yo:index>: Cannot get property 'text' on null object
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <yo:index>: Cannot get property 'text' on null object
        ... 20 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <yo:index>: Cannot get property 'text' on null object
        at gsp_unifiedScorecardsindex_gsp.run(gsp_unifiedScorecardsindex_gsp.groovy:14)
        ... 20 more
Caused by: java.lang.NullPointerException: Cannot get property 'text' on null object
        at yeoman.frontend.YoTagLib$_closure1.doCall(YoTagLib.groovy:10)
        ... 21 more
]]

By the way, we are using grails 2.5.4. Please help!!!

**Comment by bgawel** [comment]
Sorry for not responding earlier but I was on vacations. 
I have never tested the plugin against GlassFish but I am guessing that there is a problem with loading your index.html. How does the content of your war file look like? It should be something like it: 
+views             
+index.html
+js 
+META-INF
+WEB-INF
etc.

BTW: https://github.com/bgawel/yeoman-frontend/blob/master/scripts/_Events.groovy -> eventCreateWarStart is responsible for assembling the fronted into a WAR file.

**Comment by yangufsu** [comment]
I believe the packaging is right.  The expanded war file structure does look correct as you described. However, It loads the views/index.gsp as homepage instead of the index.html under the root dir of the war. The only content in views/index.gsp is <yo:index/>. That's why it says <yo:index/> i not recognized.

I have tried to update the dist folder to views/. However, it still doesn't work.

Any help will be appreciated. Many thanks.

Yan

**Comment by bgawel** [comment]
What is the result of issuing the following command in the WAR file?

ServletContextHolder.servletContext.getResourceAsStream("index.html")

**Comment by yangufsu** [comment]
I tried that in a test controller. It is null.  I have tried both "index.html" and "/index.html". Here is the code:

render(servletContext.getResourceAsStream("/index.html"))

**Comment by bgawel** [comment]
So you have already identified a problem: you just cannot access your resources. It's not related to the plugin itself but to your server configuration.

**Comment by bgawel** [comment]
BTW: have you checked if the YoResourceLocatorService.init is called? (https://github.com/bgawel/yeoman-frontend/issues/2)

**Comment by yangufsu** [comment]
I have tried this in my test controller:

def input = ServletContextHolder.servletContext.getResourceAsStream("/index.html")
render input.text

I was able to get some index.html content from the output. In this case I think the resources can be accessed through glassfish server.

**Comment by bgawel** [comment]
If you was able to get content for getResourceAsStream("/index.html"), please try to set `yo.frontend.app.index = /index.html` for your prod (war) config.

**Comment by yangufsu** [comment]
That works!!!

Thank you so much. This issue has been resolved.

**Comment by bgawel** [comment]
The other configuration options you will find in the "Configuration" section of http://bgawel.github.io/yeoman-frontend/guide/introduction.html
